version: '3.8'

services:

  mysql:
    image: mysql:8.2.0
    container_name: user_management_mysql
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - user_management_network

  redis:
    image: redis:7.2.3
    container_name: user_management_redis
    ports:
      - "6379:6379"
    networks:
      - user_management_network

networks:
  user_management_network:
